Change the import from werkzeug
python 3.6, werkzeug 1.0, on ubuntu 18.04 in WSL (Windows) I couldn't run due to the error
```    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename'
```